ALTER TABLE PRICE_MODALITY ADD MULTIPLIER NUMBER(5, 3);
ALTER TABLE PRICE_MODALITY ADD MULTIPLIER_ACCRUAL NUMBER(5, 3);
ALTER TABLE PRICE_MODALITY ADD MARKUP NUMBER(5, 3);

ALTER TABLE ORDERS_ITEM_PRICE ADD MULTIPLIER NUMBER(5, 3);
ALTER TABLE ORDERS_ITEM_PRICE ADD MULTIPLIER_ACCRUAL NUMBER(5, 3);
ALTER TABLE ORDERS_ITEM_PRICE ADD MARKUP NUMBER(5, 3);