CREATE TABLE COUNTER (
  ID INT NOT NULL,
  PROCESS VARCHAR2(255) NOT NULL,
  COUNT INT NOT NULL
);

ALTER TABLE COUNTER ADD CONSTRAINT PK_COUNTER_ID PRIMARY KEY (ID) ENABLE;
ALTER TABLE ORDERS ADD COUNTER_ID INT NOT NULL;
ALTER TABLE ORDERS ADD CONSTRAINT fk_ORDERS_counter_id FOREIGN KEY(COUNTER_ID) REFERENCES COUNTER (ID);
