ALTER TABLE FLIGHT_LEG MODIFY AIRLINE_MANGED_BY_IATA VARCHAR2(255);
ALTER TABLE FLIGHT_LEG RENAME COLUMN AIRLINE_MANGED_BY_IATA TO AIRLINE_MANAGED_BY_IATA;

ALTER TABLE FLIGHT_LEG MODIFY AIRLINE_MANGED_BY_DESCRIPTION VARCHAR2(255);
ALTER TABLE FLIGHT_LEG RENAME COLUMN AIRLINE_MANGED_BY_DESCRIPTION TO AIRLINE_MANAGED_BY_DESCRIPTION;

ALTER TABLE FLIGHT_LEG MODIFY AIRLINE_OPERATED_BY_IATA VARCHAR2(255);
ALTER TABLE FLIGHT_LEG MODIFY AIRLINE_OPERATED_BY_DESCRIPTION VARCHAR2(255);

