ALTER TABLE SEGMENT DROP COLUMN DESTINATION_DESCRIPTION;
ALTER TABLE SEGMENT DROP COLUMN ORIGIN_DESCRIPTION;
ALTER TABLE SEGMENT ADD AIRLINE_IATA VARCHAR(255) NULL;
ALTER TABLE SEGMENT ADD AIRLINE_DESCRIPTION VARCHAR(255) NULL;
ALTER TABLE SEGMENT ADD ORIGIN_CITY VARCHAR(255) NULL;
ALTER TABLE SEGMENT ADD ORIGIN_AIRPORT VARCHAR(255) NULL;
ALTER TABLE SEGMENT ADD DESTINATION_CITY VARCHAR(255) NULL;
ALTER TABLE SEGMENT ADD DESTINATION_AIRPORT VARCHAR(255) NULL;
ALTER TABLE SEGMENT ADD CABIN_CLASS VARCHAR(255) NULL;

ALTER TABLE LUGGAGE ADD QUANTITY INT NULL;
ALTER TABLE LUGGAGE ADD MEASUREMENT VARCHAR(255) NULL;
ALTER TABLE LUGGAGE ADD WEIGHT NUMBER(10,2) NULL;

ALTER TABLE FLIGHT_LEG DROP COLUMN DESTINATION_DESCRIPTION;
ALTER TABLE FLIGHT_LEG DROP COLUMN ORIGIN_DESCRIPTION;
ALTER TABLE FLIGHT_LEG ADD ORIGIN_CITY VARCHAR(255) NULL;
ALTER TABLE FLIGHT_LEG ADD ORIGIN_AIRPORT VARCHAR(255) NULL;
ALTER TABLE FLIGHT_LEG ADD DESTINATION_CITY VARCHAR(255) NULL;
ALTER TABLE FLIGHT_LEG ADD DESTINATION_AIRPORT VARCHAR(255) NULL;
ALTER TABLE FLIGHT_LEG ADD FARE_BASIS VARCHAR(255) NULL;
ALTER TABLE FLIGHT_LEG ADD FARE_CLASS VARCHAR(255) NULL;
ALTER TABLE FLIGHT_LEG ADD AIRCRAFT_CODE VARCHAR(255) NULL;
