ALTER TABLE ORDERS_STATUS DROP COLUMN STATUS_DATE;
ALTER TABLE ORDERS_STATUS RENAME TO ORDERS_STATUS_HISTORY;
CREATE TABLE ORDERS_CURRENT_STATUS(
    ID INT NOT NULL,
    CODE VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(255) NOT NULL,
    PARTNER_CODE VARCHAR2(255),
    PARTNER_DESCRIPTION VARCHAR2(255),
    PARTNER_RESPONSE CLOB,
    ORDER_ID VARCHAR2(255) NULL,
    CREATE_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);
CREATE SEQUENCE ORDERS_CURRENT_STATUS_SEQ START WITH 1;
CREATE INDEX ORDERS_CURRENT_STATUS_ORDER_ID_INDEX on ORDERS_CURRENT_STATUS(ORDER_ID) online;