ALTER TABLE DOCUMENT MODIFY COLUMN ISSUE_DATE VARCHAR2(10) NULL;
ALTER TABLE DOCUMENT MODIFY COLUMN ISSUING_COUNTRY VARCHAR2(100) NULL;
ALTER TABLE DOCUMENT MODIFY COLUMN EXPIRATION_DATE VARCHAR2(10) NULL;
ALTER TABLE DOCUMENT MODIFY COLUMN RESIDENCE_COUNTRY VARCHAR2(100) NULL;