CREATE TABLE PROCESS_COUNTER (
  ID INT NOT NULL,
  PROCESS VARCHAR2(255) NOT NULL,
  COUNT INT NOT NULL
);

CREATE SEQUENCE PROCESS_COUNTER_SEQ START WITH 1;
ALTER TABLE PROCESS_COUNTER ADD CONSTRAINT PK_PROCESS_COUNTER_ID PRIMARY KEY (ID) ENABLE;
ALTER TABLE ORDERS ADD PROCESS_COUNTER_ID INT;
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_PROCESS_COUNTER_ID FOREIGN KEY(PROCESS_COUNTER_ID) REFERENCES PROCESS_COUNTER(ID);