ALTER TABLE SEGMENT DROP COLUMN DESTINATION_DESCRIPTION;
ALTER TABLE SEGMENT DROP COLUMN ORIGIN_DESCRIPTION;
ALTER TABLE SEGMENT ADD COLUMN AIRLINE_IATA VARCHAR(255);
ALTER TABLE SEGMENT ADD COLUMN AIRLINE_DESCRIPTION VARCHAR(255);
ALTER TABLE SEGMENT ADD COLUMN ORIGIN_CITY VARCHAR(255);
ALTER TABLE SEGMENT ADD COLUMN ORIGIN_AIRPORT VARCHAR(255);
ALTER TABLE SEGMENT ADD COLUMN DESTINATION_CITY VARCHAR(255);
ALTER TABLE SEGMENT ADD COLUMN DESTINATION_AIRPORT VARCHAR(255);
ALTER TABLE SEGMENT ADD COLUMN CABIN_CLASS VARCHAR(255);

ALTER TABLE LUGGAGE ADD COLUMN QUANTITY INT;
ALTER TABLE LUGGAGE ADD COLUMN MEASUREMENT VARCHAR(255);
ALTER TABLE LUGGAGE ADD COLUMN WEIGHT NUMBER;

ALTER TABLE FLIGHT_LEG DROP COLUMN DESTINATION_DESCRIPTION;
ALTER TABLE FLIGHT_LEG DROP COLUMN ORIGIN_DESCRIPTION;
ALTER TABLE FLIGHT_LEG ADD COLUMN ORIGIN_CITY VARCHAR(255);
ALTER TABLE FLIGHT_LEG ADD COLUMN ORIGIN_AIRPORT VARCHAR(255);
ALTER TABLE FLIGHT_LEG ADD COLUMN DESTINATION_CITY VARCHAR(255);
ALTER TABLE FLIGHT_LEG ADD COLUMN DESTINATION_AIRPORT VARCHAR(255);
ALTER TABLE FLIGHT_LEG ADD COLUMN FARE_BASIS VARCHAR(255);
ALTER TABLE FLIGHT_LEG ADD COLUMN FARE_CLASS VARCHAR(255);
ALTER TABLE FLIGHT_LEG ADD COLUMN AIRCRAFT_CODE VARCHAR(255);
