ALTER TABLE ORDERS_PRICE MODIFY (AMOUNT NUMBER(20,4));
ALTER TABLE ORDERS_PRICE MODIFY (POINTS_AMOUNT NUMBER(20,4));
ALTER TABLE ORDERS_PRICE MODIFY (PARTNER_AMOUNT NUMBER(20,4));
ALTER TABLE ORDERS_PRICE MODIFY (ACCRUAL_POINTS NUMBER(20,4));


ALTER TABLE ORDERS_ITEM_PRICE MODIFY (AMOUNT NUMBER(20,4));
ALTER TABLE ORDERS_ITEM_PRICE MODIFY (POINTS_AMOUNT NUMBER(20,4));
ALTER TABLE ORDERS_ITEM_PRICE MODIFY (PARTNER_AMOUNT NUMBER(20,4));
ALTER TABLE ORDERS_ITEM_PRICE MODIFY (ACCRUAL_POINTS NUMBER(20,4));

ALTER TABLE PRICE_MODALITY MODIFY (AMOUNT NUMBER(20,4));
ALTER TABLE PRICE_MODALITY MODIFY (POINTS_AMOUNT NUMBER(20,4));
ALTER TABLE PRICE_MODALITY MODIFY (ACCRUAL_POINTS NUMBER(20,4));
