DECLARE
col_count NUMBER;
BEGIN
SELECT COUNT(*)
INTO col_count
FROM user_tab_columns
WHERE table_name = 'ORDERS_PRICE'
  AND column_name = 'POINTS_MULTIPLIER';

IF col_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ORDERS_PRICE DROP POINTS_MULTIPLIER';
END IF;
END;
/

DECLARE
col_count NUMBER;
BEGIN
SELECT COUNT(*)
INTO col_count
FROM user_tab_columns
WHERE table_name = 'ORDERS_PRICE'
  AND column_name = 'MARKUP';

IF col_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ORDERS_PRICE DROP MARKUP';
END IF;
END;
/

DECLARE
col_count NUMBER;
BEGIN
SELECT COUNT(*)
INTO col_count
FROM user_tab_columns
WHERE table_name = 'ORDERS_PRICE'
  AND column_name = 'ACCRUAL_MULTIPLIER';

IF col_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ORDERS_PRICE DROP ACCRUAL_MULTIPLIER';
END IF;
END;
/

DROP TABLE PRICE_MODALITY;


DECLARE
seq_count NUMBER;
BEGIN
SELECT COUNT(*)
INTO seq_count
FROM user_sequences
WHERE sequence_name = 'PRICE_MODALITY_SEQ';

IF seq_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP SEQUENCE PRICE_MODALITY_SEQ';
END IF;
END;
/

-- CREATE TABLE PRICE_MODALITY (
--     ID INT NOT NULL,
--     AMOUNT NUMBER(10,2),
--     POINTS_AMOUNT NUMBER(10,2),
--     ACCRUAL_POINTS NUMBER(10,2),
--     PRICE_LIST_ID VARCHAR(255),
--     ORDER_PRICE_ID INT NOT NULL
-- );
-- CREATE SEQUENCE PRICE_MODALITY_SEQ START WITH 1;
-- ALTER TABLE PRICE_MODALITY ADD CONSTRAINT PK_PRICE_MODALITY_ID PRIMARY KEY (ID) ENABLE;
-- CREATE INDEX ORDER_PRICE_ID_PRICE_MODALITY_INDEX on PRICE_MODALITY(ORDER_PRICE_ID) online;
-- COMMENT ON COLUMN PRICE_MODALITY.PRICE_LIST_ID is 'id da regra de preço vinda da calculadora';
--
-- ALTER TABLE ORDERS_PRICE ADD POINTS_MULTIPLIER NUMBER(5,2);
-- ALTER TABLE ORDERS_PRICE ADD MARKUP NUMBER(5,2);
-- ALTER TABLE ORDERS_PRICE ADD ACCRUAL_MULTIPLIER NUMBER(5,2);
--
-- ALTER TABLE SEGMENT MODIFY PARTNER_ID CLOB;