ALTER TABLE TRAVEL_INFO RENAME COLUMN ADULT_QUANTITY TO ADT;
ALTER TABLE TRAVEL_INFO RENAME COLUMN CHILD_QUANTITY TO CHD;
ALTER TABLE TRAVEL_INFO RENAME COLUMN BABY_QUANTITY TO INF;
ALTER TABLE TRAVEL_INFO RENAME COLUMN TYPE_CLASS TO CABIN_CLASS;