ALTER TABLE DOCUMENT MODIFY (ISSUE_DATE VARCHAR2(10) NULL);
ALTER TABLE DOCUMENT MODIFY (ISSUING_COUNTRY VARCHAR2(100) NULL);
ALTER TABLE DOCUMENT MODIFY (EXPIRATION_DATE VARCHAR2(10) NULL);
ALTER TABLE DOCUMENT MODIFY (RESIDENCE_COUNTRY VARCHAR2(100) NULL);